const RouteName = {
    SPLSH: "SplashScreen",
    SWIPER_SCREEN: "Swiperscreen",
    LOGIN_SCREEN: "LoginScreen",
    REGISTER_SCREEN: "Register",
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
    HOME_SCREEN: "HomeScreen",
    SIDE_NAVIGATOR: "SideNavigator",
    REGIATRAION_SUCCESSFULL: "RegistrationSuccessful",
    HOME_TAB: 'Home',
    MESSAGE_TAB: 'Message',
    ARRIVING: 'Arrivings',
    CHOOSE_TRIP: 'ChooseTrips',
    PROFILE_TAB: 'Profiles',
    SELECT_LANGUAGE: 'TranslationScreen',
    Forget_Password: 'ForgotPassword',
    CHAT_SCREEN: 'Chatscreen',
    HELP_SCREEN: 'HelpScreen',
    SETTING_SCREEN: 'SettingsScreen',
    FAQ_SCREEN: 'FAQScreen',
    REVIEWS_SCREEN: 'ReviewsScreen',
    NOTIFICTION_SCREEN: 'NotificationScreen',
    SELECTION_ADDRESS_SCREEN: "SelectAddress",
    WHERE_TO_SCREEN: "WhereToScreen",
    DRIVER_SELECT_SCREEN: "DriverSelectScreen",
    PAYMENT_SCREEN: "PaymentScreen",
    PATMENT_SUCCESSFULL_SCREEN: "PaytmSuccessFully",
    CREDIT_CARD_SCREEN: "CreditCardScreen",
    CANCEL_TRIP_SCREEN: "CancelTripScreen"
}
export default RouteName;