const images = {
   First_Swiper: require('./LottieAnimation/FirstSwiper.json'),
   Two_Swiper: require('./LottieAnimation/TwoSwiper.json'),
   Three_Swiper: require('./LottieAnimation/ThreeSwiper.json'),
   Splash_Swiper: require('./LottieAnimation/SplashScreen.json'),
   Account_created: require('./LottieAnimation/Accountcreated.json'),
   Languageanimation: require('./LottieAnimation/languageanimation.json'),
   App_logo: require('./one_fifty.png'),
   Color_picker_image: require('./colorpicker.png'),
   Reviewsimage_screen: require('./LottieAnimation/Reviewsimage.json'),
   Chat_image_one: require('./seventy.png'),
   Chat_image_two: require('./seventy.png'),
   Chat_image_three: require('./seventy.png'),
   Chat_image_four: require('./seventy.png'),
   Chat_image_five: require('./seventy.png'),
   Chat_image_six: require('./seventy.png'),
   Chat_image_saven: require('./seventy.png'),
   HomeProfileImg: require('./hundred.png'),
   CarIcon: require('./sixty.png'),
   CarDriverTwo: require('./hundred.png'),
   CarDriverThree: require('./hundred.png'),
   gpay_upi_img: require('./upiicon.png'),
   paytem_img: require('./paytem.png'),
   Mobikwikimage_img: require('./Mobikwikimage.png'),
   freechargelogo_img: require('./freechargelogo.png'),
   gpay_img: require('./gpaylogoimage.png'),
   paypal_img: require('./paypal.png'),
   creditcard_img: require('./Two_ten_four_twenty.png'),
   Pymentsuceeful_img: require('./Two_hundred.png'),
   endlocation: require('./endlocation.png'),
   circle: require('./circle.png'),
   ProfileImg: require('./hundred.png'),
   Notification_1: require('./one_fifty.png'),
   Notification_2: require('./one_fifty.png'),
}
export default images;